- hosts: localhost
  become: yes

  roles:
    - name: Install Vault
      role: vault-install

    - name: Init Vault
      role: vault-init
      
    - name: Audit
      role: vault-audit

    - name: Approle
      role: vault-approle
      
#    - name: Namespaces
#      role: vault-namespaces

    - name: AWS auth
      role: vault-aws-auth     
      
