vault_zip_path: /tmp/vault.zip
vault_bin_path: "/usr/local/bin"
vault_bin: "/usr/local/bin/vault"
vault_conf: "/etc/vault.d/vault.hcl"
vault_log: "/var/log/vault/vault.log"
tls_disable: 1
service_name: "vault"
vault_port: 8200
vault_cluster_port: 8201
vault_user: "vault"
vault_uid: "8201"
vault_group: "vault"
vault_gid: "8201"
vault_service: "vault"
vault_raft_path: "/opt/vault/"
vault_profile: "/etc/profile.d/vault.sh"
vault_path: "/etc/vault.d/"
vault_zip_url: "https://releases.hashicorp.com/vault/1.7.1+ent/vault_1.7.1+ent_linux_amd64.zip"
vault_addr: "127.0.0.1"
kms_key: "985f577d-7855-40ce-9d73-22924d0c5e15"
vault_region: "us-east-1"
